# Generated by Django 4.2.5 on 2025-09-04 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
                ('icon', models.CharField(default='up', max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(default='WIRE TRANSFER', max_length=50)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Approved', max_length=50)),
                ('mode', models.CharField(default='modal', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=50, null=True)),
                ('firstname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('account_balance', models.IntegerField(default=0)),
                ('account_pin', models.IntegerField(default=0)),
                ('dp', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pictures/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended')], default='Active', max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='up', max_length=50)),
                ('color', models.CharField(default='green', max_length=50)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(default='WIRE TRANSFER', max_length=50)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Approved', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
