# Generated by Django 4.2.5 on 2025-09-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='account_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='history',
            name='reference',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='history',
            name='to_account',
            field=models.CharField(default='', max_length=100),
        ),
    ]
